# Generated by Django 5.0.7 on 2024-08-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_profile_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='sender',
            new_name='reciever',
        ),
        migrations.RemoveField(
            model_name='form',
            name='url',
        ),
    ]
