# Generated by Django 5.0.7 on 2024-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_rename_sender_form_reciever_remove_form_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='formurl',
            name='apikey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
