# Generated by Django 5.0.7 on 2024-08-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_formurl_baseurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='formurl',
            name='userid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
