# Generated by Django 5.0.7 on 2024-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_formurl_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='formurl',
            name='demotextfield',
            field=models.TextField(blank=True, null=True),
        ),
    ]
