# Generated by Django 5.0.7 on 2024-08-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_remove_formurl_demotextfield_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='organization',
        ),
    ]
