# Generated by Django 5.0.7 on 2024-08-05 04:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_deal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formurl',
            new_name='Company',
        ),
    ]
