# Generated by Django 5.0.7 on 2024-08-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_rename_formurl_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='apikey',
            new_name='apitoken',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='products',
            new_name='deal',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='notes',
            new_name='note',
        ),
    ]
