# Generated by Django 5.0.7 on 2024-08-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_alter_company_baseurl_alter_company_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
