# Generated by Django 5.0.7 on 2024-08-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_company_webhook_url_alter_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_data',
            name='params',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
